"""
PDF Export Engine for Project KISAN.
Generates printable session reports, full history, and acreage multi-sample PDFs using ReportLab.
Features clean white background, green project header, and a centered faint green watermark logo.
Exports strictly to the project downloads/ directory.
"""

import math, os
from datetime import datetime
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def get_downloads_dir() -> str:
    """Return project downloads directory path strictly."""
    proj_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    proj_downloads = os.path.join(proj_dir, "downloads")
    os.makedirs(proj_downloads, exist_ok=True)
    return proj_downloads


def get_project_downloads_dir() -> str:
    """Return project downloads directory path strictly."""
    return get_downloads_dir()


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass Canvas for white background, green header, footer, and centered faint green watermark logo.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer_watermark(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer_watermark(self, page_count):
        self.saveState()

        # 1. White Background Canvas
        self.setFillColor(HexColor("#ffffff"))
        self.rect(0, 0, 612, 792, fill=True, stroke=False)

        # 2. Large Centered Faint Green Watermark Logo in Middle of Page
        self.saveState()
        self.translate(306, 396)  # Page center (612/2, 792/2)

        # Draw Faint Green Circular Seedling Logo Base
        self.setFillColor(HexColor("#22c55e"), alpha=0.07)
        self.setStrokeColor(HexColor("#166534"), alpha=0.10)
        self.setLineWidth(3)
        self.circle(0, 0, 110, fill=True, stroke=True)

        # Faint Green Watermark Text
        self.setFont("Helvetica-Bold", 34)
        self.setFillColor(HexColor("#166534"), alpha=0.08)
        self.drawCentredString(0, -10, "PROJECT KISAN")

        self.setFont("Helvetica", 12)
        self.drawCentredString(0, -35, "Healthy Soil, Better Tomorrow")
        self.restoreState()

        # 3. Top Header Bar with Project Name & Green Accent
        self.setFillColor(HexColor("#f0fdf4"))
        self.rect(36, 735, 540, 42, fill=True, stroke=False)

        self.setStrokeColor(HexColor("#22c55e"))
        self.setLineWidth(1.5)
        self.line(36, 735, 576, 735)

        self.setFont("Helvetica-Bold", 14)
        self.setFillColor(HexColor("#166534"))
        self.drawString(48, 750, "PROJECT KISAN")

        self.setFont("Helvetica", 10)
        self.setFillColor(HexColor("#374151"))
        self.drawRightString(564, 750, "Smart Offline Soil Analysis & Crop Recommendation")

        # 4. Footer Line & Page Number
        self.setStrokeColor(HexColor("#22c55e"))
        self.setLineWidth(0.8)
        self.line(36, 45, 576, 45)

        self.setFont("Helvetica", 9)
        self.setFillColor(HexColor("#6b7280"))
        self.drawString(36, 30, "Generated by Project KISAN • KVK Soil Analysis System")
        self.drawRightString(576, 30, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


class PDFExporter:
    """PDF Report Generator."""

    @staticmethod
    def export_acreage_report(acres: float, num_samples: int, samples_data: list, avg_data: dict, farmer_name: str = "Farmer") -> str:
        """
        Generate detailed Acreage Multi-Sample Soil Analysis PDF report.
        Saves strictly to the project downloads/ directory.
        """
        filename = f"KISAN_Acreage_Report_{acres}Acre_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(get_downloads_dir(), filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=70,
            bottomMargin=60,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontSize=16,
            textColor=HexColor("#166534"),
            spaceAfter=8,
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=HexColor("#4b5563"),
            spaceAfter=12,
        )
        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontSize=10,
            textColor=HexColor("#1f2937"),
            leading=14,
        )

        elements = []
        elements.append(Paragraph("Acreage Multi-Sample Soil Analysis Report", title_style))
        elements.append(Paragraph(f"Field Area: <b>{acres} Acre(s)</b> • Required Samples Analyzed: <b>{num_samples} Samples</b>", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=HexColor("#22c55e"), spaceAfter=14))

        # Metadata Section Table
        meta_data = [
            [Paragraph("<b>Farmer / Field Owner:</b>", body_style), Paragraph(farmer_name, body_style)],
            [Paragraph("<b>Date & Time:</b>", body_style), Paragraph(datetime.now().strftime("%d %b %Y, %I:%M %p"), body_style)],
            [Paragraph("<b>Farm Size (Acres):</b>", body_style), Paragraph(f"{acres} Acre(s)", body_style)],
            [Paragraph("<b>Sampling Formula:</b>", body_style), Paragraph(f"{num_samples} Probe Samples Collected (Formula: 1 Acre = 5 Samples, 0.5 Acre = 3 Samples)", body_style)],
        ]
        meta_table = Table(meta_data, colWidths=[150, 390])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), HexColor("#f0fdf4")),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('BOX', (0, 0), (-1, -1), 1, HexColor("#22c55e")),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#dcfce7")),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 14))

        # Averaged Soil Telemetry Table
        elements.append(Paragraph("<b>Averaged Field Telemetry Summary</b>", title_style))
        avg_rows = [["Soil Parameter", "Average Value", "Qualitative Health Evaluation"]]

        params_map = [
            ("pH Level", f"{avg_data['ph']:.2f} pH", avg_data['tags']['ph']),
            ("Nitrogen (N)", f"{avg_data['nitrogen']:.1f} mg/kg", avg_data['tags']['nitrogen']),
            ("Phosphorus (P)", f"{avg_data['phosphorus']:.1f} mg/kg", avg_data['tags']['phosphorus']),
            ("Potassium (K)", f"{avg_data['potassium']:.1f} mg/kg", avg_data['tags']['potassium']),
            ("Soil Moisture", f"{avg_data['moisture']:.1f} %", avg_data['tags']['moisture']),
            ("Soil Temperature", f"{avg_data['temperature']:.1f} °C", avg_data['tags']['temperature']),
        ]

        for p_name, p_val, p_tag in params_map:
            avg_rows.append([p_name, p_val, p_tag])

        avg_table = Table(avg_rows, colWidths=[180, 160, 200])
        avg_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor("#166534")),
            ('TEXTCOLOR', (0, 0), (-1, 0), HexColor("#ffffff")),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#bbf7d0")),
        ]))
        elements.append(avg_table)
        elements.append(Spacer(1, 14))

        # Breakdown Table of Individual Probe Samples
        if samples_data:
            elements.append(Paragraph("<b>Individual Probe Sample Breakdown</b>", title_style))
            samp_rows = [["Sample #", "pH", "N (mg/kg)", "P (mg/kg)", "K (mg/kg)", "Moisture (%)", "Temp (°C)"]]
            for idx, s in enumerate(samples_data, start=1):
                samp_rows.append([
                    f"Sample #{idx}",
                    f"{s['ph']:.1f}" if s.get('ph') is not None else "--",
                    f"{s['nitrogen']:.1f}" if s.get('nitrogen') is not None else "--",
                    f"{s['phosphorus']:.1f}" if s.get('phosphorus') is not None else "--",
                    f"{s['potassium']:.1f}" if s.get('potassium') is not None else "--",
                    f"{s['moisture']:.1f}" if s.get('moisture') is not None else "--",
                    f"{s['temperature']:.1f}" if s.get('temperature') is not None else "--",
                ])

            samp_table = Table(samp_rows, colWidths=[80, 75, 75, 75, 75, 80, 80])
            samp_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), HexColor("#1e293b")),
                ('TEXTCOLOR', (0, 0), (-1, 0), HexColor("#ffffff")),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('PADDING', (0, 0), (-1, -1), 5),
                ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#cbd5e1")),
            ]))
            elements.append(samp_table)

        doc.build(elements, canvasmaker=NumberedCanvas)
        return filepath

    @staticmethod
    def export_single_session(session_type: str, session_data: dict, farmer_name: str) -> str:
        """Generate PDF report for a single session."""
        filename = f"KISAN_{session_type.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(get_downloads_dir(), filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=70,
            bottomMargin=60,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("DocTitle", parent=styles["Heading1"], fontSize=18, textColor=HexColor("#166534"), spaceAfter=12)
        body_style = ParagraphStyle("DocBody", parent=styles["Normal"], fontSize=10, textColor=HexColor("#1f2937"), leading=14)

        elements = []
        elements.append(Paragraph(f"Official Report: {session_type}", title_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=HexColor("#22c55e"), spaceAfter=15))

        meta_data = [
            [Paragraph("<b>Farmer Name:</b>", body_style), Paragraph(farmer_name, body_style)],
            [Paragraph("<b>Date & Time:</b>", body_style), Paragraph(datetime.now().strftime("%d %b %Y, %I:%M %p"), body_style)],
            [Paragraph("<b>Report Type:</b>", body_style), Paragraph(session_type, body_style)],
        ]
        meta_table = Table(meta_data, colWidths=[120, 420])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), HexColor("#f0fdf4")),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('BOX', (0, 0), (-1, -1), 1, HexColor("#22c55e")),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 15))

        elements.append(Paragraph("<b>Session Data Details:</b>", title_style))
        content_rows = [["Parameter", "Value / Output"]]
        for k, v in session_data.items():
            content_rows.append([str(k).replace("_", " ").title(), str(v)])

        content_table = Table(content_rows, colWidths=[200, 340])
        content_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor("#166534")),
            ('TEXTCOLOR', (0, 0), (-1, 0), HexColor("#ffffff")),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#cccccc")),
        ]))
        elements.append(content_table)

        doc.build(elements, canvasmaker=NumberedCanvas)
        return filepath

    @staticmethod
    def export_full_history(sessions: list, farmer_name: str) -> str:
        """Generate PDF report for full farmer session history."""
        filename = f"KISAN_Full_History_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(get_downloads_dir(), filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=70,
            bottomMargin=60,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("DocTitle", parent=styles["Heading1"], fontSize=18, textColor=HexColor("#166534"), spaceAfter=12)

        elements = []
        elements.append(Paragraph(f"Full Farmer Session History: {farmer_name}", title_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=HexColor("#22c55e"), spaceAfter=15))

        table_rows = [["Timestamp", "Session Type", "Summary / Result"]]
        for s in sessions:
            table_rows.append([
                s.get("timestamp", "-"),
                s.get("type", "-"),
                s.get("summary", "-")
            ])

        if len(table_rows) == 1:
            table_rows.append(["-", "No sessions recorded", "-"])

        table = Table(table_rows, colWidths=[120, 150, 270])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor("#166534")),
            ('TEXTCOLOR', (0, 0), (-1, 0), HexColor("#ffffff")),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#cccccc")),
        ]))
        elements.append(table)

        doc.build(elements, canvasmaker=NumberedCanvas)
        return filepath
